# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

version: 2

orbs:
  python: circleci/python@2.0.3

  jobs:
    example-job:
      docker:
        # replace with your preferred image
        - image: cimg/base:stable
      steps:
        - python/install-packages

    workflows:
      example-workflow:
        jobs:
          - example-job


jobs:
  build:
    working_directory: ~/test
    machine: true
    steps:
      - run:
          # The Circle-CI build should not be active, but if this is not true for some reason, do a fast finish.
          command: exit 0

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /.*/

