# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

version: 2

orbs:
  python: circleci/python@2.0.3

  jobs:
    skimpy-docker-install:
      docker:
        # replace with your preferred image
        - image: danielweilandt/skimpy:latest
      steps:
        - checkout
        - python/install-packages:
            pkg-manager: pip
        - run:
            name: Run tests
            command: python -m pytest
        - persist_to_workspace:
            root: /skimpy
            paths:
              - .
              
    workflows:
      skimpy-workflow:
        jobs:
          - skimpy-docker-install

jobs:
  build:
    working_directory: ~/test
    machine: true
    steps:
      - run:
          # The Circle-CI build should not be active, but if this is not true for some reason, do a fast finish.
          command: exit 0

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /.*/

